import { parseHTML } from 'linkedom/worker'
import { trim, pick } from 'ramda'
import { encode, decode } from 'js-base64';
import { PAGE_CSS } from './template-css.js'

export function parse(page) {
  // parse html
  const { document } = parseHTML(page)
  const metaString = decode(document.head.querySelector('meta[name="Meta"]').getAttribute('content'))
  const meta = JSON.parse(metaString)
  // descontruce model
  let result = {
    contentType: 'text/html',
    type: 'page',
    title: document.head.querySelector('title').innerText,
    description: document.head.querySelector('meta[name="description"]').getAttribute('content'),
    topics: document.head.querySelector('meta[name="keywords"]').getAttribute('content').split(',').map(trim),
    content: decode(document.head.querySelector('meta[name="Content"]').getAttribute('content')),
    html: document.body.innerHTML,
    creator: document.head.querySelector('meta[name="Creator"]').getAttribute('content'),
    ...meta

  }
  return result
}

export function htmlify(page, head) {
  return createHtml(page, head)
}


function createHtml(page) {
  return `<!doctype html>
<html data-theme="${page.theme}">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${page.title}</title>
    <meta name="description" content="${page.description}">
    <meta name="keywords" content="${page.topics.join(', ')}">
    <meta name="Protocol-Name" content="${page.protocol}">
    <meta name="Content" content="${encode(page.content)}">
    <meta name="Timestamp" content="${page.timestamp}">
    <meta name="Creator" content="${page.creator}">
    <meta name="Meta" content="${encode(JSON.stringify(pick(['profile', 'weavemail', 'ethwallet', 'theme', 'includeFooter', 'allowStamps', 'noContract', 'noBundlr', 'widgets', 'derivation', 'derivationValue', 'derivationValuePlus', 'commercial', 'commercialValue', 'commercialValuePlus', 'dataModelTraining', 'dataModelTrainingValue', 'dataModelTrainingValuePlus'], page)))}">
    <meta name="about" content="Webpage generated by https://pages.arweave.dev">
    <style>${PAGE_CSS}</style>
    ${page.widgets.reduce((a, w) => a + `<script defer type="module" src="${w.source}"></script>`, '')}
  </head>
  <body>
    ${page.html}
    ${page.includeFooter ? `
    <footer class="footer">
      <div>
        <span class="footer-title">Permanent page</span>
        <p>Published with <a href="https://permapages.app" target="_blank">Permapages</a> — stored forever on Arweave.</p>
      </div>
      <div>
        <a href="https://permapages.app" class="btn">Create your own Permapage</a>
      </div>
    </footer>
    ` : ''}
  </body>
</html>
  `
}