import { parseHTML } from 'linkedom/worker'
import Async from 'crocks/Async/index.js'
import { assoc, lens, lensProp, trim, split, over, identity, compose, prop, filter, find, path, propEq, map, pluck, __, head, uniqBy, join, omit } from 'ramda'
import { encode, decode } from 'js-base64';
import { buildPostTags } from '../services/tags.js'
import { PAGE_CSS } from '../services/template-css.js'

const lensHtml = lens(identity, assoc('html'))

export default function ({ gql, publish, getData }) {
  function get(id) {
    return Async.of(id)
      .map(buildFindByIdQuery)
      .chain(Async.fromPromise(gql))
      .chain(edges => {
        const asset = compose(
          head,
          filter(n => find(t => t.name === 'Type', n.tags).value === 'blog-post' && find(t => t.name === 'Uploader', n.tags) === undefined),
          pluck('node')
        )(edges)
        if (asset.tags.find(propEq('Protocol-Name', 'name'))?.value === 'Permapage-Post-v4') {
          return Async.fromPromise(getData)(asset.id)
            .map(
              (a) => ({
                ...toPostItem(asset),
                content: loadContent(a.data), // need to parse html and de-serialize source
                html: a.data
              })
            )
        } else {
          return Async.of(asset.tags.find(propEq('Asset-Id', 'name'))?.value)
            .map(id => ({ query: buildSourceQuery(), variables: { ids: [id] } }))
            .chain(Async.fromPromise(gql))
            .map(path(['0', 'node', 'id']))
            .chain(Async.fromPromise(getData))
            .map(a => ({
              ...toPostItem(asset),
              content: a.data
            }))
        }

      })
  }

  function create(post) {
    // markdown-it (+ compose-time hljs) loads only when actually publishing
    const loadMd = Async.fromPromise(() =>
      import('../services/md.js').then(({ md, enableCodeHighlight }) =>
        enableCodeHighlight(md).then(() => md)))
    return loadMd()
      .chain(md => Async.of(post)
      .map(p => p.assetId ? p : assoc('assetId', crypto.randomUUID(), p))
      .map(over(lensHtml, generateHtml(md)))
      .map(over(lensProp('topics'), compose(map(trim), split(','))))
      .map(post => {
        const topicTags = map(v => ({ name: `Topic:${v}`, value: v }), post.topics)
        return {
          asset: {
            data: post.html,
            tags: buildPostTags(post, topicTags)
          }
        }
      })
      .chain(Async.fromPromise(publish))
      .map(({ id }) => assoc('id', id, post)))
  }

  function list(addr) {
    return Async.of(addr)
      .map(buildQuery)
      .chain(Async.fromPromise(gql))
      .map(pluck('node'))
      .map(map(toPostItem))
      .map(uniqBy(prop('assetId')))
  }
  return {
    list,
    create,
    get
  }
}
//tags: { name: "Asset-Id", values: $ids }
function buildFindByIdQuery(id) {
  return {
    query: `query ($ids: [ID!]!, $cursor: String) {
      transactions(first: 1, after: $cursor, ids: $ids) {
        pageInfo {
          hasNextPage
        }
        edges {
          cursor
          node {
            id
            owner {
              address
            }
            tags {
              name
              value
            }
          }
        }
      }
    }`,
    variables: {
      ids: [id]
    }
  }
}

function buildQuery(addr) {
  return {
    query: `query ($owners: [String!], $cursor: String) {
      transactions(first: 100, 
        after: $cursor, 
        owners: $owners, 
        tags: [
          { name: "Type", values: ["blog-post"] }
        ]) {
        pageInfo {
          hasNextPage
        }
        edges {
          cursor
          node {
            id
            owner {
              address
            }
            tags {
              name
              value
            }
          }
        }
      }
    }`,
    variables: {
      owners: [addr]
    }
  }
}

function toPostItem(node) {
  const getTag = compose(prop('value'), n => find(propEq(n, 'name'), node.tags))
  const published = getTag('Published') ? Number(getTag('Published')) : Date.now()
  const topics = join(', ', pluck('value', filter(t => /^Topic:/.test(t.name), node.tags)))
  const protocol = getTag('Protocol-Name') || 'PermaPages-Post-v0.3'

  return {
    id: node.id,
    type: getTag('Type'),
    title: getTag('Title'),
    description: getTag('Description'),
    protocol: protocol,
    transaction: node.id,
    assetId: getTag('Asset-Id'),
    published,
    stamps: 0,
    owner: node.owner.address,
    topics
  }
}

function generateHtml(md) {
  return (post) => `<!doctype html>
<html data-theme="light">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>${post.title}</title>
    <meta name="description" content="${post.description}">
    <meta name="author" content="${post.profile.owner}">
    <meta name="code" content="${post.id}">
    <meta name="about" content="Webpage generated by https://pages.arweave.dev">
    <meta name="source" content="${encode(JSON.stringify(omit(['profile'], post)))}">
    <style>${PAGE_CSS}</style>
  </head>
  <body>
    <main>
      <article class="prose">
        <h1>${post.title}</h1>
        <p>${post.description}</p>
        <div class="byline">
          <img src=${post.profile.avatar} alt=${post.profile.name} />
          <div>
            <div class="name">${post.profile.name}</div>
            <div class="date">Published ${new Intl.DateTimeFormat('en-US').format(Date.now())}</div>
          </div>
        </div>
        ${md.render(post.content)}
      </article>
    </main>
  </body>
</html>

  `
}

function loadContent(html) {
  const { document } = parseHTML(html)
  const source = document.head.querySelector('meta[name="source"]').getAttribute('content')
  const post = JSON.parse(decode(source))
  return post.content
}

function buildSourceQuery() {
  return `query ($ids: [String!]!) {
  transactions(first: 1, tags: [
    {name: "Asset-Id", values: $ids },
    {name: "Type", values: ["post-source"]}
  ]) {
    pageInfo {
      hasNextPage
    }
    edges {
      node {
        id
      }
    }
  }
  }`
}